export GAME1='{"name": "Metaphor ReFantazio", "developer": "Atlus"}'
export GAME2='{"name": "Astro Bot", "developer": "Sony"}'
export GAME3='{"name": "Animal Well", "developer": "Billy Basso"}'
export GAME4='{"name": "Balatro", "developer": "LocalThunk"}'
export GAME5='{"name": "Hades 2", "developer": "Supergiant"}'
